# Generated by Django 3.1.2 on 2020-10-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201018_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanicprofile',
            name='last_name',
        ),
    ]
