# Generated by Django 3.1.2 on 2020-10-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(null=True)),
                ('message', models.TextField(default=0, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('catagory', models.CharField(max_length=50, null=True)),
                ('Status_Closed', models.BooleanField(default=False)),
            ],
        ),
    ]
