# Generated by Django 3.1.2 on 2020-10-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message1',
            old_name='phone',
            new_name='phoneno',
        ),
    ]
