- name: auto-dependabot-pull-request-merge
  # You may pin to the exact commit or the version.
  # uses: KeisukeYamashita/auto-dependabot-pull-request-merge@a7ac708f2c3b0c28e86ad099d6ce7f2a5219fd94
  uses: KeisukeYamashita/auto-dependabot-pull-request-merge@v1
  with:
    # Check all status before merge
    checkStatus: # optional, default is true
    # Comment before merge
    comment: # optional, default is 
    # Seconds between the check
    intervalSeconds: # optional, default is 0.1
    # Fail the step if the PR is not found or merged
    failStep: # optional, default is true
    # Comma seperated labes that target pull request should have
    labels: # optional, default is 
    # Comma seperated labes that target pull request should not have
    ignoreLabels: # optional, default is 
    # The GitHub repository containing the issue or pr.
    repository: # optional, default is ${{ github.repository }}
    # Number of the pull request
    pullRequestNumber: # optional, default is ${{ github.event.pull_request.number }}
    # SHA of the pull request commit
    sha: # optional, default is ${{ github.event.pull_request.head.sha }}
    # Merge strategy
    strategy: # optional, default is merge
    # Seconds to timeout
    timeoutSeconds: # optional, default is 60
    # Credential to access to the repo to post the comment
    token: # optional, default is ${{ github.token }}
